# Generated by Django 5.2.1 on 2025-06-04 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueJob',
            fields=[
                ('id', models.BigAutoField(help_text='Primary key for the queue job', primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('face_extraction', 'Face Extraction'), ('tags', 'Tags')], help_text='Type of job to be processed', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the job was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the job was last updated')),
                ('picture', models.ForeignKey(help_text='Picture to be processed', on_delete=django.db.models.deletion.CASCADE, related_name='queue_jobs', to='gallery.picture')),
            ],
            options={
                'verbose_name': 'Queue Job',
                'verbose_name_plural': 'Queue Jobs',
                'ordering': ['created_at'],
            },
        ),
    ]
