# Generated by Django 5.2.1 on 2025-06-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuejob',
            name='job_type',
            field=models.CharField(choices=[('face_extraction_dnn', 'Face Extraction (DNN)'), ('face_extraction_haar', 'Face Extraction (Haar Cascade)'), ('tags', 'Tags')], help_text='Type of job to be processed', max_length=20),
        ),
    ]
