# Generated by Django 5.2.1 on 2025-06-04 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceExtraction',
            fields=[
                ('id', models.BigAutoField(help_text='Primary key for the face extraction', primary_key=True, serialize=False)),
                ('bbox_x', models.IntegerField(help_text='X coordinate of the bounding box top-left corner')),
                ('bbox_y', models.IntegerField(help_text='Y coordinate of the bounding box top-left corner')),
                ('bbox_width', models.IntegerField(help_text='Width of the bounding box')),
                ('bbox_height', models.IntegerField(help_text='Height of the bounding box')),
                ('confidence', models.FloatField(help_text='Confidence score of the face detection')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the face extraction was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the face extraction was last updated')),
                ('picture', models.ForeignKey(help_text='Picture from which faces are extracted', on_delete=django.db.models.deletion.CASCADE, related_name='face_extractions', to='gallery.picture')),
            ],
            options={
                'verbose_name': 'Face Extraction',
                'verbose_name_plural': 'Face Extractions',
                'ordering': ['created_at'],
            },
        ),
    ]
