# Generated by Django 5.2.1 on 2025-06-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceextraction',
            name='algorithm',
            field=models.CharField(choices=[('haar', 'Haar Cascade'), ('dnn', 'DNN Enhanced')], default='haar', help_text='Algorithm used for face extraction', max_length=10),
        ),
    ]
