# Generated by Django 5.2.1 on 2025-06-03 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the picture', max_length=255)),
                ('image', models.ImageField(help_text='Image file of the picture', upload_to='pictures/')),
                ('description', models.TextField(blank=True, help_text='Description of the picture', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the picture was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the picture was last updated')),
                ('miniature', models.ImageField(blank=True, help_text='Miniature version of this picture (optional)', null=True, upload_to='miniatures/')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tag', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the tag', null=True)),
                ('classification', models.CharField(blank=True, help_text='Classification of the tag (optional)', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the processing was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the processing was last updated')),
                ('picture', models.ForeignKey(help_text='Picture to be processed', on_delete=django.db.models.deletion.CASCADE, related_name='processing_queue', to='gallery.picture')),
            ],
            options={
                'verbose_name': 'Processing Queue',
                'verbose_name_plural': 'Processing Queues',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='picture',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this picture', related_name='pictures', to='gallery.tag'),
        ),
    ]
