# Generated by Django 5.2.1 on 2025-06-04 17:13

import gallery.service
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(help_text='Primary key for the picture', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the picture', max_length=255)),
                ('image', models.ImageField(help_text='Image file of the picture', upload_to=gallery.service.hash_upload_path)),
                ('description', models.TextField(blank=True, help_text='Description of the picture', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the picture was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the picture was last updated')),
                ('miniature', models.ImageField(blank=True, help_text='Miniature version of this picture (optional)', null=True, upload_to=gallery.service.miniature_upload_path)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags associated with this picture', related_name='pictures', to='tagging.tag')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
                'ordering': ['title'],
            },
        ),
    ]
