# Generated by Django 5.2.1 on 2025-06-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_processingqueue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='id',
            field=models.BigAutoField(help_text='Primary key for the picture', primary_key=True, serialize=False),
        ),
    ]
