# Generated by Django 5.2.1 on 2025-06-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_picture_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(help_text='Primary key for the tag', primary_key=True, serialize=False),
        ),
    ]
