# Generated by Django 5.2.1 on 2025-06-04 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_tag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagClassification',
            fields=[
                ('id', models.BigAutoField(help_text='Primary key for the tag classification', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the tag classification', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tag Classification',
                'verbose_name_plural': 'Tag Classifications',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='tag',
            name='classification',
            field=models.ForeignKey(blank=True, help_text='Classification of the tag', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='gallery.tagclassification'),
        ),
    ]
