# Generated by Django 5.2.1 on 2025-06-04 03:36

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_tagclassification_alter_tag_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(help_text='Image file of the picture', upload_to=gallery.models.hash_upload_path),
        ),
        migrations.AlterField(
            model_name='picture',
            name='miniature',
            field=models.ImageField(blank=True, help_text='Miniature version of this picture (optional)', null=True, upload_to=gallery.models.miniature_upload_path),
        ),
    ]
