# Generated by Django 5.2.1 on 2025-06-04 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagClassification',
            fields=[
                ('id', models.BigAutoField(help_text='Primary key for the tag classification', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the tag classification', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tag Classification',
                'verbose_name_plural': 'Tag Classifications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(help_text='Primary key for the tag', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the tag', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the tag', null=True)),
                ('classification', models.ForeignKey(blank=True, help_text='Classification of the tag', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tagging.tagclassification')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
    ]
